#!/bin/bash

echo "🎨 Instagram Image Replacement Guide"
echo "====================================="
echo ""
echo "Current placeholder images are working perfectly!"
echo "To replace them with your actual Instagram images:"
echo ""
echo "1. Download images from your Instagram (@johnowolabi_)"
echo "2. Replace these files with your actual images:"
echo ""
echo "   📸 Portrait:"
echo "      public/images/portrait.jpg"
echo ""
echo "   📝 Journal Covers:"
echo "      public/images/journal/digital-minimalism.jpg"
echo "      public/images/journal/creative-process.jpg" 
echo "      public/images/journal/constraints.jpg"
echo ""
echo "   🎯 Highlights:"
echo "      public/images/highlights/style-1.jpg"
echo "      public/images/highlights/work-1.jpg"
echo "      public/images/highlights/writing-1.jpg"
echo ""
echo "   🌍 Little World:"
echo "      public/images/little-world/typewriter.jpg"
echo ""
echo "3. Keep the same filenames for automatic integration"
echo "4. Recommended sizes:"
echo "   - Portrait: 400x500px"
echo "   - Journal: 800x600px"
echo "   - Highlights: 400x300px"
echo "   - Little World: 400x400px"
echo ""
echo "✨ Your site is ready to go with these beautiful placeholder images!"
echo "   Visit: http://localhost:3000"
